/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import estructural.Estudiante;

/**
 *
 * @author felip
 */
public class GUIPanelInfo extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form GUIPanelInfo
     */
    
    private GUIPrincipal guiPrincipal;
    
    private int modo;
    
    private Estudiante estudiante;
    
    //Modo 1: Registrar - Modo 2: Actualizar - Modo 3: Visualizar Modo 4: borrar
    public GUIPanelInfo(GUIPrincipal pGui, int pModo) {
        guiPrincipal = pGui;
        modo = pModo;
        initComponents();
        ponerImagen();
        
        JDateChooser jdFechaNacimiento = new JDateChooser();
        panelCalendario.add(jdFechaNacimiento);
        jdFechaNacimiento.setBounds(0,0, 390, 20);
         
        if(pModo == 1){
            habilitarEdicion(true);
            habilitarBoton(true, 1);
        }
        else if(pModo == 2){
            habilitarEdicion(true);
            habilitarBoton(true, 2);
        }
        else if(pModo == 3){
            habilitarEdicion(false);
            habilitarBoton(false, 3);
        }
        else if(pModo == 4){
            habilitarEdicion(false);
            habilitarBoton(true, 4);
        }
       
        
        btAccion.addActionListener(this);
        btAccion.setActionCommand("ACCION");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtDNI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtRH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtEps = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtTelf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtDireccion = new javax.swing.JTextField();
        imagenPersona = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        btAccion = new javax.swing.JButton();
        panelCalendario = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha Nacimiento: (Día/Mes/Año)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 220, 20));

        jLabel2.setText("Nombres:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 60, 20));

        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 60, 20));

        jtApellido.setEditable(false);
        jPanel1.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 180, -1));

        jtNombre.setEditable(false);
        jPanel1.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 180, -1));

        jLabel5.setText("EPS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 150, 20));

        jtDNI.setEditable(false);
        jPanel1.add(jtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 390, -1));

        jLabel6.setText("Factor RH:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 150, 20));

        jtRH.setEditable(false);
        jPanel1.add(jtRH, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 180, -1));

        jLabel7.setText("Documento de identificación:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 200, 20));

        jtEps.setEditable(false);
        jPanel1.add(jtEps, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 180, -1));

        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 150, 20));

        jtTelf.setEditable(false);
        jtTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelfActionPerformed(evt);
            }
        });
        jPanel1.add(jtTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 180, -1));

        jLabel9.setText("Correo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 150, 20));

        jtCorreo.setEditable(false);
        jtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 180, -1));

        jLabel10.setText("Dirección de la casa:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 150, 20));

        jtDireccion.setEditable(false);
        jtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(jtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 390, -1));
        jPanel1.add(imagenPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 290, 290));

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTitulo.setText("REGISTRAR ESTUDIANTE");
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 280, -1));

        btAccion.setText("REGISTRAR ESTUDIANTE");
        jPanel1.add(btAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 180, -1));

        panelCalendario.setLayout(null);
        jPanel1.add(panelCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 390, 20));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelfActionPerformed

    private void jtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCorreoActionPerformed

    private void jtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDireccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccion;
    private javax.swing.JLabel imagenPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtDNI;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtEps;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtRH;
    private javax.swing.JTextField jtTelf;
    private javax.swing.JPanel panelCalendario;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

    public void ponerImagen()
    {
        imagenPersona.setIcon(new ImageIcon(this.getClass().getResource("/img/user.png")));
    }
    
    public void habilitarBoton(boolean pEdit, int modo)
    {
        btAccion.setVisible(pEdit);
        if(modo == 1){
            txtTitulo.setText("Registrar Estudiante");
            btAccion.setText("Registrar Estudiante");
        }else if(modo == 2){
            txtTitulo.setText("Actualizar Estudiante");
            btAccion.setText("Actualizar Estudiante");
        }else if(modo == 3){
            txtTitulo.setText("Visualizar Estudiante");
        }
        else if(modo == 4){
            txtTitulo.setText("Borrar Estudiante");
            btAccion.setText("Borrar Estudiante");
        }
    }
    
    public void habilitarEdicion(boolean pEdit)
    {
        //fECHA
        jtNombre.setEditable(pEdit);
        jtApellido.setEditable(pEdit);
        jtDNI.setEditable(pEdit);
        jtRH.setEditable(pEdit);
        jtEps.setEditable(pEdit);
        jtCorreo.setEditable(pEdit);
        jtDireccion.setEditable(pEdit);
        jtTelf.setEditable(pEdit);
    }
    
    public void refrescarInfo(Estudiante pEstudiante)
    {
        //Fecha
        estudiante = pEstudiante;
        jtNombre.setText(pEstudiante.getNombres());
        jtApellido.setText(pEstudiante.getApellidos());
        jtDNI.setText(pEstudiante.getDocumento());
        jtRH.setText(pEstudiante.getrH());
        jtEps.setText(pEstudiante.getEps());
        jtCorreo.setText(pEstudiante.getCorreo());
        jtDireccion.setText(pEstudiante.getDireccion());
        jtTelf.setText(pEstudiante.getTelefono());
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        
        int hora = 0, min = 0;
        LocalDateTime date = LocalDateTime.now();
        Estudiante estActual = new Estudiante(jtNombre.getText(), jtApellido.getText(), date, 
                jtDNI.getText(), jtRH.getText(), jtEps.getText(), jtTelf.getText(), jtDireccion.getText(), jtCorreo.getText());
        if(modo == 1){
            if(jtNombre.getText().trim().isEmpty() == true || jtApellido.getText().trim().isEmpty() == true){
                JOptionPane.showMessageDialog(guiPrincipal, "Tienes que insertar al menos los nombres del usuario");
            }
            else{
                guiPrincipal.registrarEstudiante(estActual);
                JOptionPane.showMessageDialog(guiPrincipal, "¡Se ha registrado el estudiante correctamente!");
                guiPrincipal.uiVerLista();
            }
        }
        else if(modo == 2){//Actualizarlo
            guiPrincipal.actualizarEstudiante(estudiante.getDocumento(), estActual);
            JOptionPane.showMessageDialog(guiPrincipal, "¡Se ha actualizado el estudiante correctamente!");
            guiPrincipal.uiVerLista();
        }
        else if(modo == 4){//Actualizarlo
            int select = JOptionPane.showOptionDialog(guiPrincipal, "¿Está seguro de querer eliminar el estudiante?", "IMPORTANTE", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, 1);
            if(select == 0)
            {
                guiPrincipal.borrarEstudiante(estudiante.getDocumento());
                JOptionPane.showMessageDialog(guiPrincipal, "¡Se ha borrado el estudiante correctamente!");
                guiPrincipal.uiVerLista();
            }
        }
    }
    
}
