/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import estructural.Estudiante;
import estructural.Matricula;
import java.awt.Dimension;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ServicioLocalEstudiante;
import model.ServicioLocalMatricula;

/**
 *
 * @author felip
 */
public class JDialogBuscarEstudiante extends javax.swing.JFrame {

    private ArrayList<Estudiante> estudiantes;
    private JPanel padre;
    private JFrame padre2;
    private int modo;
    /**
     * Creates new form JDialogBuscarEstudiante
     */
    
    public JDialogBuscarEstudiante(JPanel pPadre,  int pModo) throws RemoteException {
        padre = pPadre;
        modo = pModo;
        initComponents();
        setTitle("Buscar Estudiante");
        setLocationRelativeTo(null);
        setSize(new Dimension(390, 530));
        
        cambiarDatosTabla(1);
    }
    
    public void ponerPadreFrame(JFrame pd){
        padre2 = pd;
    }
    
    private void cambiarDatosTabla(int pModo) throws RemoteException{
        DefaultTableModel modelo = (DefaultTableModel)tablaDatos.getModel();
        modelo.getDataVector().removeAllElements();
        revalidate();
        
        estudiantes = ServicioLocalEstudiante.getServicio().darEstudiantesPorNombre(txtFilto.getText());
        
        for (int i = 0; i < estudiantes.size(); i++) {
            Vector fila = new Vector();
            fila.add(estudiantes.get(i).getDocumento());
            fila.add(estudiantes.get(i).getNombres() + " " + estudiantes.get(i).getApellidos());
            modelo.addRow(fila);
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFilto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiantes"));

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre"
            }
        ));
        tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 340, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 58, 88));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUSCAR ESTUDIANTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtFilto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltoActionPerformed(evt);
            }
        });
        jPanel2.add(txtFilto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, -1));

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 13, 90, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            cambiarDatosTabla(0);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "No hay registros con ese nombre en la base de datos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseClicked
        int column = 0;
        int row = tablaDatos.getSelectedRow();
        String value = tablaDatos.getModel().getValueAt(row, column).toString();
        try {
            if(modo == 1){
                GUIPanelMatricula p = (GUIPanelMatricula) padre;
                p.actualizarInformacion(ServicioLocalEstudiante.getServicio().buscarEstudiante(value));
            }else if(modo == 2){
                JDialogBuscarMatriculaEstudiante matri = (JDialogBuscarMatriculaEstudiante) padre2;
                matri.actualizarInformacion(ServicioLocalEstudiante.getServicio().buscarEstudiante(value));
            }
            else if(modo == 3){
                mostrarPromedioEstudiante(ServicioLocalEstudiante.getServicio().buscarEstudiante(value));
            }
        }catch (RemoteException ex) {
                Logger.getLogger(JDialogBuscarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_tablaDatosMouseClicked


    public void mostrarPromedioEstudiante(Estudiante pEst) throws RemoteException{
        System.out.println("Entré");
        Matricula mat = new Matricula(); 
        mat.setPkEstudiante(pEst.getDocumento());
        double nota = ServicioLocalMatricula.getServicio().darPromedioEstudiante(mat);
        System.out.println(nota);
        JOptionPane.showMessageDialog(this, "El promedio del estudiante " + pEst.getNombres() + " " + pEst.getApellidos() + "es de: " + nota);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField txtFilto;
    // End of variables declaration//GEN-END:variables
}
